# Q1.Find the percentage of population of India who speaks (a) only one language, (b) exactly two languages, and (c) three languages or more.

In [1]:
import pandas as pd
import os
import warnings
warnings.filterwarnings('ignore')

In [2]:
#Census data loading
census_2011 ="Census2011data.xlsx"
df_census=pd.read_excel(census_2011,usecols= ["State","Level","Name","TRU","TOT_P"])

In [3]:
#Census data preprocessing

df_census=df_census[df_census["TRU"]=="Total"]

df_census =df_census[df_census["Level"] != "DISTRICT"]

df_census["State"] = df_census["State"].astype(int)

df_census.rename(columns={'State':'State Code','Name':'State Name'},inplace=True)

df_census = df_census[["State Code","State Name","TOT_P"]]

df_census['State Name']=df_census['State Name'].str.upper()

df_census.reset_index(drop=True,inplace=True)

In [4]:
df_census

    State Code                 State Name       TOT_P
0            0                      INDIA  1210854977
1            1            JAMMU & KASHMIR    12541302
2            2           HIMACHAL PRADESH     6864602
3            3                     PUNJAB    27743338
4            4                 CHANDIGARH     1055450
5            5                UTTARAKHAND    10086292
6            6                    HARYANA    25351462
7            7               NCT OF DELHI    16787941
8            8                  RAJASTHAN    68548437
9            9              UTTAR PRADESH   199812341
10          10                      BIHAR   104099452
11          11                     SIKKIM      610577
12          12          ARUNACHAL PRADESH     1383727
13          13                   NAGALAND     1978502
14          14                    MANIPUR     2855794
15          15                    MIZORAM     1097206
16          16                    TRIPURA     3673917
17          17                  MEGHALAYA     2966889
18          18                      ASSAM    31205576
19          19                WEST BENGAL    91276115
20          20                  JHARKHAND    32988134
21          21                     ODISHA    41974218
22          22               CHHATTISGARH    25545198
23          23             MADHYA PRADESH    72626809
24          24                    GUJARAT    60439692
25          25                DAMAN & DIU      243247
26          26       DADRA & NAGAR HAVELI      343709
27          27                MAHARASHTRA   112374333
28          28             ANDHRA PRADESH    84580777
29          29                  KARNATAKA    61095297
30          30                        GOA     1458545
31          31                LAKSHADWEEP       64473
32          32                     KERALA    33406061
33          33                 TAMIL NADU    72147030
34          34                 PUDUCHERRY     1247953
35          35  ANDAMAN & NICOBAR ISLANDS      380581

In [5]:
#loading c18
c18="DDW-C18-0000.xlsx"
df_c18=pd.read_excel(c18,skiprows=[0,4,5])
df_c18=df_c18[["State","Area Name","Total/","Age-group","Number speaking second language","Number speaking third language"]]

#c18 preprocessing
df_c18=df_c18[df_c18["Age-group"]=="Total"]
df_c18=df_c18[df_c18["Total/"]=="Total"]

df_c18.rename(columns = {'Area Name':'State Name','State':'State Code'},inplace=True)
df_c18["State Code"] = df_c18["State Code"].astype(int)

df_c18.drop(["Total/","Age-group"],axis=1,inplace=True)
df_c18.reset_index(drop=True,inplace=True)

In [6]:
df_c18

,State Code,State Name,Number speaking second language,Number speaking third language
0,0,INDIA,314988770,86009580
1,1,JAMMU & KASHMIR,6183190,2096220
2,2,HIMACHAL PRADESH,1242705,347286
3,3,PUNJAB,13035224,7829913
4,4,CHANDIGARH,579920,321979
5,5,UTTARAKHAND,1757756,187822
6,6,HARYANA,5627361,1170571
7,7,NCT OF DELHI,6817214,1358233
8,8,RAJASTHAN,7473186,1006751
9,9,UTTAR PRADESH,22873609,2585664
10,10,BIHAR,16761785,1682572
11,11,SIKKIM,388999,181402
12,12,ARUNACHAL PRADESH,885945,418551
13,13,NAGALAND,1229723,537481
14,14,MANIPUR,1388620,616818
15,15,MIZORAM,309703,52966
16,16,TRIPURA,1268601,198577
17,17,MEGHALAYA,822320,274931
18,18,ASSAM,14460591,4352497
19,19,WEST BENGAL,15025848,2881005
20,20,JHARKHAND,10000720,1593039
21,21,ODISHA,13825024,5525278
22,22,CHHATTISGARH,3384223,422569
23,23,MADHYA PRADESH,9808682,1257953
24,24,GUJARAT,25892341,8570571
25,25,DAMAN & DIU,116629,34602
26,26,DADRA & NAGAR HAVELI,198983,71516
27,27,MAHARASHTRA,57419861,19724729
28,28,ANDHRA PRADESH,21583334,6344376
29,29,KARNATAKA,24252594,7832129
30,30,GOA,1126152,741249
31,31,LAKSHADWEEP,18553,9981
32,32,KERALA,8163387,3188813
33,33,TAMIL NADU,20416270,2447163
34,34,PUDUCHERRY,392292,71665
35,35,ANDAMAN & NICOBAR ISLANDS,257425,72708

In [7]:
#merge df_census and df_c18 

df_merge = pd.merge(df_census,df_c18,how='inner',left_on='State Code',right_on = 'State Code')
df_merge

,State Code,State Name_x,TOT_P,State Name_y,Number speaking second language,Number speaking third language
0,0,INDIA,1210854977,INDIA,314988770,86009580
1,1,JAMMU & KASHMIR,12541302,JAMMU & KASHMIR,6183190,2096220
2,2,HIMACHAL PRADESH,6864602,HIMACHAL PRADESH,1242705,347286
3,3,PUNJAB,27743338,PUNJAB,13035224,7829913
4,4,CHANDIGARH,1055450,CHANDIGARH,579920,321979
5,5,UTTARAKHAND,10086292,UTTARAKHAND,1757756,187822
6,6,HARYANA,25351462,HARYANA,5627361,1170571
7,7,NCT OF DELHI,16787941,NCT OF DELHI,6817214,1358233
8,8,RAJASTHAN,68548437,RAJASTHAN,7473186,1006751
9,9,UTTAR PRADESH,199812341,UTTAR PRADESH,22873609,2585664
10,10,BIHAR,104099452,BIHAR,16761785,1682572
11,11,SIKKIM,610577,SIKKIM,388999,181402
12,12,ARUNACHAL PRADESH,1383727,ARUNACHAL PRADESH,885945,418551
13,13,NAGALAND,1978502,NAGALAND,1229723,537481
14,14,MANIPUR,2855794,MANIPUR,1388620,616818
15,15,MIZORAM,1097206,MIZORAM,309703,52966
16,16,TRIPURA,3673917,TRIPURA,1268601,198577
17,17,MEGHALAYA,2966889,MEGHALAYA,822320,274931
18,18,ASSAM,31205576,ASSAM,14460591,4352497
19,19,WEST BENGAL,91276115,WEST BENGAL,15025848,2881005
20,20,JHARKHAND,32988134,JHARKHAND,10000720,1593039
21,21,ODISHA,41974218,ODISHA,13825024,5525278
22,22,CHHATTISGARH,25545198,CHHATTISGARH,3384223,422569
23,23,MADHYA PRADESH,72626809,MADHYA PRADESH,9808682,1257953
24,24,GUJARAT,60439692,GUJARAT,25892341,8570571
25,25,DAMAN & DIU,243247,DAMAN & DIU,116629,34602
26,26,DADRA & NAGAR HAVELI,343709,DADRA & NAGAR HAVELI,198983,71516
27,27,MAHARASHTRA,112374333,MAHARASHTRA,57419861,19724729
28,28,ANDHRA PRADESH,84580777,ANDHRA PRADESH,21583334,6344376
29,29,KARNATAKA,61095297,KARNATAKA,24252594,7832129
30,30,GOA,1458545,GOA,1126152,741249
31,31,LAKSHADWEEP,64473,LAKSHADWEEP,18553,9981
32,32,KERALA,33406061,KERALA,8163387,3188813
33,33,TAMIL NADU,72147030,TAMIL NADU,20416270,2447163
34,34,PUDUCHERRY,1247953,PUDUCHERRY,392292,71665
35,35,ANDAMAN & NICOBAR ISLANDS,380581,ANDAMAN & NICOBAR ISLANDS,257425,72708

In [8]:
#calculate only one language, exactly two languages and Three languages or more speakers

df_merge["Only one language"] = df_merge["TOT_P"]-df_merge["Number speaking second language"]
df_merge["exactly two languages"] = df_merge["Number speaking second language"] - df_merge["Number speaking third language"]
df_merge["Three languages or more"] = df_merge["Number speaking third language"]
df_merge

,State Code,State Name_x,TOT_P,State Name_y,Number speaking second language,Number speaking third language,Only one language,exactly two languages,Three languages or more
0,0,INDIA,1210854977,INDIA,314988770,86009580,895866207,228979190,86009580
1,1,JAMMU & KASHMIR,12541302,JAMMU & KASHMIR,6183190,2096220,6358112,4086970,2096220
2,2,HIMACHAL PRADESH,6864602,HIMACHAL PRADESH,1242705,347286,5621897,895419,347286
3,3,PUNJAB,27743338,PUNJAB,13035224,7829913,14708114,5205311,7829913
4,4,CHANDIGARH,1055450,CHANDIGARH,579920,321979,475530,257941,321979
5,5,UTTARAKHAND,10086292,UTTARAKHAND,1757756,187822,8328536,1569934,187822
6,6,HARYANA,25351462,HARYANA,5627361,1170571,19724101,4456790,1170571
7,7,NCT OF DELHI,16787941,NCT OF DELHI,6817214,1358233,9970727,5458981,1358233
8,8,RAJASTHAN,68548437,RAJASTHAN,7473186,1006751,61075251,6466435,1006751
9,9,UTTAR PRADESH,199812341,UTTAR PRADESH,22873609,2585664,176938732,20287945,2585664
10,10,BIHAR,104099452,BIHAR,16761785,1682572,87337667,15079213,1682572
11,11,SIKKIM,610577,SIKKIM,388999,181402,221578,207597,181402
12,12,ARUNACHAL PRADESH,1383727,ARUNACHAL PRADESH,885945,418551,497782,467394,418551
13,13,NAGALAND,1978502,NAGALAND,1229723,537481,748779,692242,537481
14,14,MANIPUR,2855794,MANIPUR,1388620,616818,1467174,771802,616818
15,15,MIZORAM,1097206,MIZORAM,309703,52966,787503,256737,52966
16,16,TRIPURA,3673917,TRIPURA,1268601,198577,2405316,1070024,198577
17,17,MEGHALAYA,2966889,MEGHALAYA,822320,274931,2144569,547389,274931
18,18,ASSAM,31205576,ASSAM,14460591,4352497,16744985,10108094,4352497
19,19,WEST BENGAL,91276115,WEST BENGAL,15025848,2881005,76250267,12144843,2881005
20,20,JHARKHAND,32988134,JHARKHAND,10000720,1593039,22987414,8407681,1593039
21,21,ODISHA,41974218,ODISHA,13825024,5525278,28149194,8299746,5525278
22,22,CHHATTISGARH,25545198,CHHATTISGARH,3384223,422569,22160975,2961654,422569
23,23,MADHYA PRADESH,72626809,MADHYA PRADESH,9808682,1257953,62818127,8550729,1257953
24,24,GUJARAT,60439692,GUJARAT,25892341,8570571,34547351,17321770,8570571
25,25,DAMAN & DIU,243247,DAMAN & DIU,116629,34602,126618,82027,34602
26,26,DADRA & NAGAR HAVELI,343709,DADRA & NAGAR HAVELI,198983,71516,144726,127467,71516
27,27,MAHARASHTRA,112374333,MAHARASHTRA,57419861,19724729,54954472,37695132,19724729
28,28,ANDHRA PRADESH,84580777,ANDHRA PRADESH,21583334,6344376,62997443,15238958,6344376
29,29,KARNATAKA,61095297,KARNATAKA,24252594,7832129,36842703,16420465,7832129
30,30,GOA,1458545,GOA,1126152,741249,332393,384903,741249
31,31,LAKSHADWEEP,64473,LAKSHADWEEP,18553,9981,45920,8572,9981
32,32,KERALA,33406061,KERALA,8163387,3188813,25242674,4974574,3188813
33,33,TAMIL NADU,72147030,TAMIL NADU,20416270,2447163,51730760,17969107,2447163
34,34,PUDUCHERRY,1247953,PUDUCHERRY,392292,71665,855661,320627,71665
35,35,ANDAMAN & NICOBAR ISLANDS,380581,ANDAMAN & NICOBAR ISLANDS,257425,72708,123156,184717,72708

In [9]:
#calculate the percentages for the above 

df_merge["percent-one"] = ((df_merge["Only one language"] *100)/df_merge["TOT_P"]).astype(float).round(2).astype(str)+"%"
df_merge["percent-two"] = ((df_merge["exactly two languages"] *100)/df_merge["TOT_P"]).astype(float).round(2).astype(str)+"%"
df_merge["percent-three"] = ((df_merge["Three languages or more"] *100)/df_merge["TOT_P"]).astype(float).round(2).astype(str)+"%"
df_merge

,State Code,State Name_x,TOT_P,State Name_y,Number speaking second language,Number speaking third language,Only one language,exactly two languages,Three languages or more,percent-one,percent-two,percent-three
0,0,INDIA,1210854977,INDIA,314988770,86009580,895866207,228979190,86009580,73.99%,18.91%,7.1%
1,1,JAMMU & KASHMIR,12541302,JAMMU & KASHMIR,6183190,2096220,6358112,4086970,2096220,50.7%,32.59%,16.71%
2,2,HIMACHAL PRADESH,6864602,HIMACHAL PRADESH,1242705,347286,5621897,895419,347286,81.9%,13.04%,5.06%
3,3,PUNJAB,27743338,PUNJAB,13035224,7829913,14708114,5205311,7829913,53.01%,18.76%,28.22%
4,4,CHANDIGARH,1055450,CHANDIGARH,579920,321979,475530,257941,321979,45.05%,24.44%,30.51%
5,5,UTTARAKHAND,10086292,UTTARAKHAND,1757756,187822,8328536,1569934,187822,82.57%,15.57%,1.86%
6,6,HARYANA,25351462,HARYANA,5627361,1170571,19724101,4456790,1170571,77.8%,17.58%,4.62%
7,7,NCT OF DELHI,16787941,NCT OF DELHI,6817214,1358233,9970727,5458981,1358233,59.39%,32.52%,8.09%
8,8,RAJASTHAN,68548437,RAJASTHAN,7473186,1006751,61075251,6466435,1006751,89.1%,9.43%,1.47%
9,9,UTTAR PRADESH,199812341,UTTAR PRADESH,22873609,2585664,176938732,20287945,2585664,88.55%,10.15%,1.29%
10,10,BIHAR,104099452,BIHAR,16761785,1682572,87337667,15079213,1682572,83.9%,14.49%,1.62%
11,11,SIKKIM,610577,SIKKIM,388999,181402,221578,207597,181402,36.29%,34.0%,29.71%
12,12,ARUNACHAL PRADESH,1383727,ARUNACHAL PRADESH,885945,418551,497782,467394,418551,35.97%,33.78%,30.25%
13,13,NAGALAND,1978502,NAGALAND,1229723,537481,748779,692242,537481,37.85%,34.99%,27.17%
14,14,MANIPUR,2855794,MANIPUR,1388620,616818,1467174,771802,616818,51.38%,27.03%,21.6%
15,15,MIZORAM,1097206,MIZORAM,309703,52966,787503,256737,52966,71.77%,23.4%,4.83%
16,16,TRIPURA,3673917,TRIPURA,1268601,198577,2405316,1070024,198577,65.47%,29.12%,5.41%
17,17,MEGHALAYA,2966889,MEGHALAYA,822320,274931,2144569,547389,274931,72.28%,18.45%,9.27%
18,18,ASSAM,31205576,ASSAM,14460591,4352497,16744985,10108094,4352497,53.66%,32.39%,13.95%
19,19,WEST BENGAL,91276115,WEST BENGAL,15025848,2881005,76250267,12144843,2881005,83.54%,13.31%,3.16%
20,20,JHARKHAND,32988134,JHARKHAND,10000720,1593039,22987414,8407681,1593039,69.68%,25.49%,4.83%
21,21,ODISHA,41974218,ODISHA,13825024,5525278,28149194,8299746,5525278,67.06%,19.77%,13.16%
22,22,CHHATTISGARH,25545198,CHHATTISGARH,3384223,422569,22160975,2961654,422569,86.75%,11.59%,1.65%
23,23,MADHYA PRADESH,72626809,MADHYA PRADESH,9808682,1257953,62818127,8550729,1257953,86.49%,11.77%,1.73%
24,24,GUJARAT,60439692,GUJARAT,25892341,8570571,34547351,17321770,8570571,57.16%,28.66%,14.18%
25,25,DAMAN & DIU,243247,DAMAN & DIU,116629,34602,126618,82027,34602,52.05%,33.72%,14.23%
26,26,DADRA & NAGAR HAVELI,343709,DADRA & NAGAR HAVELI,198983,71516,144726,127467,71516,42.11%,37.09%,20.81%
27,27,MAHARASHTRA,112374333,MAHARASHTRA,57419861,19724729,54954472,37695132,19724729,48.9%,33.54%,17.55%
28,28,ANDHRA PRADESH,84580777,ANDHRA PRADESH,21583334,6344376,62997443,15238958,6344376,74.48%,18.02%,7.5%
29,29,KARNATAKA,61095297,KARNATAKA,24252594,7832129,36842703,16420465,7832129,60.3%,26.88%,12.82%
30,30,GOA,1458545,GOA,1126152,741249,332393,384903,741249,22.79%,26.39%,50.82%
31,31,LAKSHADWEEP,64473,LAKSHADWEEP,18553,9981,45920,8572,9981,71.22%,13.3%,15.48%
32,32,KERALA,33406061,KERALA,8163387,3188813,25242674,4974574,3188813,75.56%,14.89%,9.55%
33,33,TAMIL NADU,72147030,TAMIL NADU,20416270,2447163,51730760,17969107,2447163,71.7%,24.91%,3.39%
34,34,PUDUCHERRY,1247953,PUDUCHERRY,392292,71665,855661,320627,71665,68.57%,25.69%,5.74%
35,35,ANDAMAN & NICOBAR ISLANDS,380581,ANDAMAN & NICOBAR ISLANDS,257425,72708,123156,184717,72708,32.36%,48.54%,19.1%

In [10]:
#select required attributes 

df_final=df_merge[["State Code","percent-one","percent-two","percent-three"]]

In [11]:
df_final

    State Code percent-one percent-two percent-three
0            0      73.99%      18.91%          7.1%
1            1       50.7%      32.59%        16.71%
2            2       81.9%      13.04%         5.06%
3            3      53.01%      18.76%        28.22%
4            4      45.05%      24.44%        30.51%
5            5      82.57%      15.57%         1.86%
6            6       77.8%      17.58%         4.62%
7            7      59.39%      32.52%         8.09%
8            8       89.1%       9.43%         1.47%
9            9      88.55%      10.15%         1.29%
10          10       83.9%      14.49%         1.62%
11          11      36.29%       34.0%        29.71%
12          12      35.97%      33.78%        30.25%
13          13      37.85%      34.99%        27.17%
14          14      51.38%      27.03%         21.6%
15          15      71.77%       23.4%         4.83%
16          16      65.47%      29.12%         5.41%
17          17      72.28%      18.45%         9.27%
18          18      53.66%      32.39%        13.95%
19          19      83.54%      13.31%         3.16%
20          20      69.68%      25.49%         4.83%
21          21      67.06%      19.77%        13.16%
22          22      86.75%      11.59%         1.65%
23          23      86.49%      11.77%         1.73%
24          24      57.16%      28.66%        14.18%
25          25      52.05%      33.72%        14.23%
26          26      42.11%      37.09%        20.81%
27          27       48.9%      33.54%        17.55%
28          28      74.48%      18.02%          7.5%
29          29       60.3%      26.88%        12.82%
30          30      22.79%      26.39%        50.82%
31          31      71.22%       13.3%        15.48%
32          32      75.56%      14.89%         9.55%
33          33       71.7%      24.91%         3.39%
34          34      68.57%      25.69%         5.74%
35          35      32.36%      48.54%         19.1%

In [12]:
#write to output csv file 

outname = 'percent-india.csv'
outfiles = './Output_Files'
if not os.path.exists(outfiles):
    os.mkdir(outfiles)
outdir=outfiles+'/Q1'
if not os.path.exists(outdir):
    os.mkdir(outdir)
filepath = os.path.join(outdir, outname)    

df_final.to_csv(filepath,index=False)